### ISSUE TITLE
zlib data error

### ISSUE THREAD

**Issue by waken22** [zhad3/zextractor#3]
I'm receiving this error when using the zextractor release in windows.
I use Powershell as admin, and i suspect that some files are not properly extracted due this error.

```[Info] Parsing GRFs and loading filetables...
[Info] Finished loading filetables with a total of 37833 files after 301 ms, 762 ╬╝s, and 8 hnsecs
[Info] Extracting files...
[Info] Finished extracting after 7 secs, 362 ms, 852 ╬╝s, and 7 hnsecs

std.zlib.ZlibException@std\zlib.d(98): data error
----------------
0x00007FF7ADBF041D
0x00007FF7ADBF0196
0x00007FF7ADBEC7D0
0x00007FF7ADBC803A
0x00007FF7ADB940DF
0x00007FF7ADB93EBE
0x00007FF7ADB92AAA
0x00007FF7ADB92BF8
0x00007FF7ADB86E0D
0x00007FF7ADBCDF2D
0x00007FF7ADB6AFE2
0x00007FF7ADB68C77
0x00007FF7ADBCEF35
0x00007FF7ADBCEC07
0x00007FF7ADBCEEC3
0x00007FF7ADBF6A00
0x00007FFA7D637034 in BaseThreadInitThunk
0x00007FFA7E6E2651 in RtlUserThreadStart
```

**Comment by zhad3** [comment]
Hey, can you re-run the command with the `-v` option and pipe the output to a file.
Example command:
`zextractor -v --grf=data.grf > output.log`
The `-v` option will print the files that are being extracted. That way we can find out which file(s) failed to be extracted.
Could you try extracting them with another tool such as GRFEditor and see if it succeeds?

**Comment by waken22** [comment]
Hello again, answering your question, yes, apparently GRFEditor can extract my grf, i will try to show you more outputs.
Using the following command to extract data.grf :
```./zextractor -v --grf=data.grf > output.log```
I receive the error again :
```std.zlib.ZlibException@std\zlib.d(98): data error
----------------
0x00007FF6DB9E041D
0x00007FF6DB9E0196
0x00007FF6DB9DC7D0
0x00007FF6DB9B803A
0x00007FF6DB9840DF
0x00007FF6DB983EBE
0x00007FF6DB982AAA
0x00007FF6DB982BF8
0x00007FF6DB976E0D
0x00007FF6DB9BDF2D
0x00007FF6DB95AFE2
0x00007FF6DB958E83
0x00007FF6DB9BEF35
0x00007FF6DB9BEC07
0x00007FF6DB9BEEC3
0x00007FF6DB9E6A00
0x00007FFA7D637034 in BaseThreadInitThunk
0x00007FFA7E6E2651 in RtlUserThreadStart
```

I don't know if this helps but using zextractor on docker gives me this error on the same grf :
```
std.zlib.ZlibException@std/zlib.d(98): data error
----------------
??:? <ERROR: Unable to retrieve function name> [0x5564e720eb10]
??:? <ERROR: Unable to retrieve function name> [0x5564e7210110]
??:? <ERROR: Unable to retrieve function name> [0x5564e71f2cd0]
??:? <ERROR: Unable to retrieve function name> [0x5564e71bb260]
??:? <ERROR: Unable to retrieve function name> [0x5564e71bb190]
??:? <ERROR: Unable to retrieve function name> [0x5564e71baa20]
??:? <ERROR: Unable to retrieve function name> [0x5564e71babb0]
??:? <ERROR: Unable to retrieve function name> [0x5564e71adea0]
??:? <ERROR: Unable to retrieve function name> [0x5564e71f1bd0]
??:? <ERROR: Unable to retrieve function name> [0x5564e7197cf0]
??:? <ERROR: Unable to retrieve function name> [0x5564e7195c70]
??:? <ERROR: Unable to retrieve function name> [0x5564e71f2a10]
??:? <ERROR: Unable to retrieve function name> [0x5564e71f27c0]
??:? <ERROR: Unable to retrieve function name> [0x5564e71f2720]
```

I upload my data.grf on google drive:
https://drive.google.com/file/d/1A-ojM0tKfsoWiaolmoEvuzvVwo8INNdZ/view

This is the output generated:
[output.log](https://github.com/zhad3/zextractor/files/7877595/output.log)
It stopped at 11239???

**Comment by zhad3** [comment]
Thank you for providing the GRF. I have looked into the issue and I still couldn't manage to uncompress the file `guarddog2..act`. Perhaps this has to do with different zlib versions.

I have however released a new version that will no longer stop the whole extraction when a single file fails to be extracted. If that file is truly needed I'd recommend another tool to extract that specific file.

**Comment by waken22** [comment]
Honestly i have no idea what is that file called "guarddog2.act", but whatever, the important thing is that now the extraction doesn't stop when some file cannot be extracted, so for my personal case it works :) 
Thanks!!

**Comment by zhad3** [comment]
> Same issue, 2 out of 14 tested `.thor`-files are unpacked with errors
> file: [05-24-22-cutesharkhatfix2.thor](https://files.catbox.moe/ro1ccg.thor) (74KB) 
> output: [05-24-22-cutesharkhatfix2_errors.txt](https://github.com/zhad3/zextractor/files/8941993/05-24-22-cutesharkhatfix2_errors.txt)
> 
> file: [06-20-22-summerfixes.thor](https://files.catbox.moe/bigqa2.thor) (71MB) 
> output: [06-20-22-summerfixes_errors.txt](https://github.com/zhad3/zextractor/files/8942013/06-20-22-summerfixes_errors.txt)

@morrah The reason that these two THOR patches cannot be extracted is because the files are encrypted. Currently encryption is not supported (and probably never will).

**Comment by morrah** [comment]
Thanks for the clarification!
