### ISSUE TITLE
Message: rawRead must take a non-empty buffer

### ISSUE THREAD

**Issue by LeonardoFeriato** [zhad3/zextractor#5]
Hi @zhad3 , it's me again.

When I run `zextractor.exe` in some Lua Files I got this message:
```
[Info] Couldn't read filters from file, continuing without. Message: Cannot open file `filters.txt' in mode `r' (No such file or directory)
[Info] Parsing GRFs and loading filetables...
[Info] Finished loading filetables with a total of 142200 files after 438 ms, 61 ╬╝s, and 1 hnsec
[Info] Extracting files...
[Error] An error occurred extracting the file "data\luafiles514\lua files\debugui\_debugwndinfo.lua". Message: rawRead must take a non-empty buffer
```

And I think theses errors are making the zrenderer return:
```
[WARN] Config file 'zrenderer.conf' not found
[main(----) INF] Listening for requests on http://localhost:11011/
[main(c9bH) INF] [0:0:0:0:0:0:0:1]:62171 - - 2023-Jan-26 14:13:26.2895198Z "RenderRequestData { job=[4063], action=16, gender=female, head=21, garment=48, bodyPalette=3, headPalette=6, headgear=[1985,1309,572] }" -- Token: 5k29kplxfxw3shyu4trtjn400ivhbkkw Id: 0 Desc: Auto-generated Admin Token
D:\MA\ShadowTable.lua:850: table index is nil in source\resource\lua.d:100
[main(c9bH) INF] [0:0:0:0:0:0:0:1]:62171 - - 2023-Jan-26 14:13:26.2895198Z "POST /render?accesstoken=5k29kplxfxw3shyu4trtjn400ivhbkkw HTTP/1.1" 500 50 "-" "PostmanRuntime/7.30.0"

```

What I'm doing wrong?
Follow my `zextractor.config`
[zextractor.conf.txt](https://github.com/zhad3/zextractor/files/10510048/zextractor.conf.txt)

**Comment by LeonardoFeriato** [comment]
Hi,

Now I tried with other server `data.grf` and those errors don't happen in the zextractor.
However, in zrenderer I have this
```
[WARN] Config file 'zrenderer.conf' not found
[main(----) INF] Listening for requests on http://localhost:11011/
[main(NSqM) INF] [0:0:0:0:0:0:0:1]:49769 - - 2023-Jan-26 17:22:58.2458247Z "RenderRequestData { job=[4063], action=16, gender=female, head=21, garment=48, bodyPalette=3, headPalette=6, headgear=[1985,1309,572] }" -- Token: 5k29kplxfxw3shyu4trtjn400ivhbkkw Id: 0 Desc: Auto-generated Admin Token
resolver_data/imf_names.txt: O sistema n├úo pode encontrar o caminho especificado. in std\file.d:451
[main(NSqM) INF] [0:0:0:0:0:0:0:1]:49769 - - 2023-Jan-26 17:22:58.2458247Z "POST /render?accesstoken=5k29kplxfxw3shyu4trtjn400ivhbkkw HTTP/1.1" 500 50 "-" "PostmanRuntime/7.30.0"
```

I still think that is happening the extractor's fault, could you give me some help?

**Comment by zhad3** [comment]
> [Error] An error occurred extracting the file "data\luafiles514\lua files\debugui\_debugwndinfo.lua". Message: rawRead must take a non-empty buffer
I have changed the code so these type of occurrences are not marked as "error" anymore. It is legitimate that the grf contains empty files.

> D:\MA\ShadowTable.lua:850: table index is nil in source\resource\lua.d:100
That does seem odd. Is the ShadowTable.lua file broken?

> resolver_data/imf_names.txt: O sistema n├úo pode encontrar o caminho especificado.
zrenderer requires the `resolver_data/` directory. Make sure its in the same directory from where you started the server.

**Comment by zhad3** [comment]
The message is not from zextractor but from zrenderer. Displaying the file is probably no problem (what GRF Editor does) but parsing and using it (what zrenderer) does is failing.

If the shadowtable is empty then thats the problem. When you extracted all the files you should have a ` data/luafiles514/lua files/datainfo/shadowtable.lub`  or ` .lua`  file. zrenderer is reading that.

**Comment by LeonardoFeriato** [comment]
I solved the problem using other GRF, now I'll extract only SPR and ACT from the other a want to.
You can close this issue, thank you again and congrats for this amazing job.
